baseURL: "https://mongoberto.github.io/"
languageCode : "en-us"
title : "mongoberto"
theme : "cactus"

security:
  exec:
    allow:
      - "dart-sass-embedded"
      - "go"
      - "npx"
      - "postcss"
      - "asciidoctor"

params:
  colortheme : "dark"
  description : "Welcome to my blog, I'm Guillaume, back-end developer. I post my notes, memos or other mind maps here, hoping that it will be useful to you!"
  mainSection : "posts"
    #mainSectionTitle : "Notes"
  tocInline : true
  copyright : "mongoberto"
  rss : true
  social:
    - name : "github"
      link : "https://github.com/mongoberto"
        #- name : "email"
        #link : "berto.guillaume@hotmail.fr" # no need for "mailto:" at the start
    - name : "linkedin"
      link : "https://www.linkedin.com/in/guillaumeberto/"

markup:
  highlight:
    codeFences : true
    guessSyntax : false
    hl_Lines : ""
    lineNoStart : 1
    lineNos : false
    lineNumbersInTable : true
    noClasses : true
    style : "monokai"
    tabWidth : 4
  asciidocExt:
    extensions:
      - asciidoctor-html5s
      - asciidoctor-diagram

menu:
  main:
    - name : "Home"
      url : "/"
      weight : 1
    - name : "All posts"
      url : "/posts"
      weight : 2
    - name : "Liste de lecture"
      url : "/toRead"
      weight : 3
    - name : "Tags"
      url : "/tags"
      weight : 4
    - name : "About"
      url : "/about"
      weight : 5
