baseURL = "https://mongoberto.github.io/"
languageCode = "en-us"
title = "MongoBerto"
theme = "cactus"

[params]
colortheme = "dark"
description = "Welcome to my blog, I'm Guillaume, back-end developer. I post my notes, memos or other mind maps here, hoping that it will be useful to you!"
mainSection = "posts"
mainSectionTitle = "Notes"
tocInline = true
copyright = "mongoberto"
rss = true

[[params.social]]
  name = "github"
  link = "https://github.com/mongoberto"

[[params.social]]
  name = "email"
  link = "berto.guillaume@hotmail.fr" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/guillaumeberto/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
